# Ruby is our language as asciidoctor is a ruby gem.
language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
#after_success:
#  - .travis/push.sh
#env:
#  global:
#    secure: dlzzrSS3dENwl0rrfgzkItTQ/eFUg2RjXZ5ZD2JxCeWN0S3S+QPP4NE18tONJ7P6fD/gBD9Oej+4ndMLBR65j7/khBc/KGur5HBP7cLLR5seT6ksrvPYfT1Iy9Zw0lDUNw4tUt0AI6M3hE42poKaccYueqiTORhkrQ74wtm1+WqMCc+QQpEMyuY8LmSNZq7mIrU4JVfIoS9+sFKwGTIKBprevx/FYDazuD20tEqBjuJMedkMMz85SvfMEJ3xUnaM82HrVG6A+06ZBpxndU8qgX2V3cmxefztBZm19qPC5OdEgTJ1cNJM6wwU+Qt1CF/Ws3OYizqOB1uVkm6noGcAANoWhwsLxS7ifUpaWgLphNmzbL1uYRMFaOFxZsUafwA5zSwu5NYZqcAsaEi1yFriQl/Mkhkz6GRSfuBVozV/n0XIunJhjqfJbZWciWENbVsnlxTSwhd0juDcUoxjwjwdpX5Be62Qu0Up7+GGYEVOHFMgfFTgUOKAE0S8XGW2GZ7UjOD8JFSc4X1dyPeXxu5Vrdnzl1Alrdh/TELe9we0bPMwfBgWxeI14z4U25tCjMzIGLS8SWyv1ojNAS3bQYT3CqJq6AcKL5M0TM+AUdpmnhiDP2sSucdfMh3u5x70qiCfXSS5E39fc+TKMJnc3U15a8Bgp+Gt9u4JvklKieMz6m8=
env:
  global:
  - GIT_CONFIG=.travis/travis.gitconfig
  - GH_COMMIT_AUTHOR="Travis CI"
  - GH_COMMIT_EMAIL=your_email@example.com
  secure: dlzzrSS3dENwl0rrfgzkItTQ/eFUg2RjXZ5ZD2JxCeWN0S3S+QPP4NE18tONJ7P6fD/gBD9Oej+4ndMLBR65j7/khBc/KGur5HBP7cLLR5seT6ksrvPYfT1Iy9Zw0lDUNw4tUt0AI6M3hE42poKaccYueqiTORhkrQ74wtm1+WqMCc+QQpEMyuY8LmSNZq7mIrU4JVfIoS9+sFKwGTIKBprevx/FYDazuD20tEqBjuJMedkMMz85SvfMEJ3xUnaM82HrVG6A+06ZBpxndU8qgX2V3cmxefztBZm19qPC5OdEgTJ1cNJM6wwU+Qt1CF/Ws3OYizqOB1uVkm6noGcAANoWhwsLxS7ifUpaWgLphNmzbL1uYRMFaOFxZsUafwA5zSwu5NYZqcAsaEi1yFriQl/Mkhkz6GRSfuBVozV/n0XIunJhjqfJbZWciWENbVsnlxTSwhd0juDcUoxjwjwdpX5Be62Qu0Up7+GGYEVOHFMgfFTgUOKAE0S8XGW2GZ7UjOD8JFSc4X1dyPeXxu5Vrdnzl1Alrdh/TELe9we0bPMwfBgWxeI14z4U25tCjMzIGLS8SWyv1ojNAS3bQYT3CqJq6AcKL5M0TM+AUdpmnhiDP2sSucdfMh3u5x70qiCfXSS5E39fc+TKMJnc3U15a8Bgp+Gt9u4JvklKieMz6m8=
