### GENERAL SETTINGS ###

# Site settings
title: gvSIG Roads, solución libre para gestión de carreteras
description: "Solución libre e interoperable para la gestión integral de las infraestructuras viarias."
google_analytics: UA-73596417-1 #Google analytics code in the format XX-nnnnnnnn-n
#baseurl: "/roads" #important: start with /
url: "http://www.gvsigroads.com/" #pro url
#url: "http://localhost:4000"
ASSET_PATH: /assets

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
highlighter: pygments
paginate:    2
paginate_path: "blog/page:num"


colors:  #in hex code if not noted else
  primary: "#3b8bba" #azul claro apagado
  primary_rgb: "59,139,186" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #azul oscuro
  secondary_rgb: "56,68,82"
  link: "#428bca" #azul claro
  link_hover: "#01b2fe" #azul claro
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3" #gris
  yellow_gvsig: "#E2AD2A"
  title: "#074f66" #azul heading


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  - title: linkedin
    url: http://www.linkedin.com/grp/home?gid=8478272
  - title: twitter
    url: http://twitter.com/gvsigroads


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - C/ San Vicente Mártir, 84 - 5A Valencia
    - CP 46002, Spain
    - +34 963 516 309
email: hello@gvsigroads.com
tel: (+34) 963 516 309

# Clients information. Shown on Home and About pages.
clients:
  - name: Asociación gvSIG
    img: asociacion-gvsig.png
    url: http://www.gvsig.com
    title: Asociación gvSIG website
  - name: DISID
    img: disid.png
    url: http://www.disid.com
    title: DISID Corporation website
  - name: Diputación de Valencia
    img: logo-dival.png
    url: http://www.dival.es/
    title: Diputación de Valencia website

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Gestión integral del mantenimiento y conservación de carreteras utilizando software libre con información cartográfica integrada."

# jekyll configuration

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font-awesome

#
# Multilanguage
#

defaults:
  -
    scope:
      path: ""
    values:
      lang: es
      layout:
  -
    scope:
      path: _posts/en
    values:
      lang: en
      layout:

t:
  en:
    description: Tool for rapid web application development
    headline: Higher productivity thanks to its components with high functional value for corporate applications
  es:
    description: Herramienta de desarrollo rápido de aplicaciones web
    headline: Mayor productividad gracias a sus componentes de alto valor funcional para aplicaciones corporativas

# To include variable in liquid: {{ site.t[page.lang].grid-title }}
# You can add translations group

# Links to include in top navigation
# For external links add external: true
links:
  en:
    doc:
#      title: Changelog
#      url: /en/documentation
#      external: false
  es:
    doc:
#      title: Control de cambios
#      url: /es/documentation
#      external: false


include: [".htaccess"]
exclude: ["vendor", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

