### GENERAL SETTINGS ###

# Site settings
google_analytics: UA-73596417-1 #Google analytics code in the format XX-nnnnnnnn-n
#baseurl: "/roads" #important: start with /
url: "http://www.gvsigroads.com" #pro url
#url: "http://localhost:4000"
ASSET_PATH: /assets

# Build settings
markdown: kramdown
#permalink: /:title/
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
highlighter: rouge
paginate:    2
paginate_path: "blog/page:num"

#Collection
collections:
  about:
    output: false
    #permalink: /about/:path/
  how:
    output: false
    #permalink: /how/:path/
  services:
    output: false
    #permalink: /how/:path/
  technology:
    output: false
    #permalink: /how/:path/



colors:  #in hex code if not noted else
  primary: "#3b8bba" #azul claro apagado
  primary_rgb: "59,139,186" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #azul oscuro
  secondary_rgb: "56,68,82"
  link: "#428bca" #azul claro
  link_hover: "#01b2fe" #azul claro
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3" #gris
  yellow_gvsig: "#E2AD2A"
  title: "#074f66" #azul heading


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  - title: linkedin
    url: http://www.linkedin.com/grp/home?gid=8478272
  - title: twitter
    url: http://twitter.com/gvsigroads


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Avinguda de Menéndez y Pelayo, 5 Valencia
    - CP 46010, Spain
    - +34 963 516 309
email: gvsigroads@disid.com
tel: (+34) 963 516 309

# Clients information. Shown on Home and About pages.
clients:
  - name: Asociación gvSIG
    img: asociacion-gvsig.png
    url: http://www.gvsig.com
    title: Asociación gvSIG website
  - name: DISID
    img: disid.png
    url: http://www.disid.com
    title: DISID Corporation website
  - name: Diputación de Valencia
    img: logo-dival.png
    url: http://www.dival.es/
    title: Diputación de Valencia website

# jekyll configuration

gems:
  - jekyll-asciidoc

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - idseparator=_
    - icons=font-awesome
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style

#
# Multilanguage
#

defaults:
  -
    scope:
      path: ""
    values:
      lang: es
      layout:
  -
    scope:
      path: _posts/en
    values:
      lang: en
      layout:

t:
  es:
    title: "gvSIG Roads, solución libre para gestión de carreteras"
    legal-notice: "Aviso legal"
    office: "Nuestras oficinas"
    header:
      title: "gvSIG"
      title-highlight: "Roads"
      description:
      - lines:
        - "Solución libre e interoperable"
        - "para la gestión integral de las infraestructuras viarias"
    about:
      title: "¿Qué es gvSIG Roads?"
      description:
      - lines:
        - "gvSIG Roads es una solución integral, que permite la gestión de las infraestructuras viarias tanto desde su componente alfanumérica como geográfica, basada en estándares y software libre."
        - "Implantar gvSIG Roads permite implantar un completo sistema de gestión para la conservación y el inventario de carreteras integrado con la potencia de las Infraestructuras de Datos Espaciales."
      # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
      headline: "Gestión integral del mantenimiento y conservación de carreteras utilizando software libre con información cartográfica integrada."
    how:
      title: "Flujo de trabajo con gvSIG Roads"
      description: "Incorpora funcionalidades de carácter gráfico que aportan el concepto GEO así como herramientas de análisis y toma de decisiones."
    features:
      title: "Plataforma tecnológica"
      description: "Se utilizan tecnologías contrastadas, con amplio soporte a nivel internacional, y con una curva evolutiva constante"
    video:
      title:
      - lines:
        - "La mejor solución para la gestión"
        - "de la conservación de carreteras"
      headline: "Gestión de incidencias, inventario y flujo de trabajo con gvSIG Roads"
    software:
      title: "Solución basada en una suite de aplicaciones libres"
      description:
      - lines:
        - "Libre e interoperable"
        - ""
      tools:
        - name: gvSIG Desktop
          img: logo_gvsigdesktop.png
          url: http://www.gvsig.com
          description: "Software para el manejo de información geográfica con precisión cartográfica"
        - name: gvNIX
          img: logo-gvnix-negativo.png
          url: http://www.gvnix.com
          description: "Herramienta de desarrollo rápido de aplicaciones web Java"
    portfolio:
      title: "CASOS DE ÉXITO"
      description: "Proyectos y presentaciones de la solución gvSIG Roads"
      subtitle: "La experiencia nos avala"
    clients:
      title: "DESARROLLADO POR"
      description: "Organizaciones involucradas en el proyecto"
    banner:
      title: "gvSIG Roads"
      description: "Plataforma integral de gestión de carreteras"
      call-to-action: "¡Quiero recibir más información!"
    contact:
      title: "¿Quieres utilizar gvSIG Roads en tus proyectos?"
      description:
      - lines:
        - "¡Genial, buena elección!"
        - "Llámanos o envía un email, como prefieras, y nos pondremos en contacto contigo lo antes posible."
      company: Soy una empresa
      council: Soy un ayuntamiento
    suscribe:
      title: "¿Quieres ver una demo de gvSIG Roads?"
      email: "Tu email *"
      email-message: "Por favor, escribe tu dirección de correo electrónico."
      button: "¡Quiero tener acceso a la demo!"
      description:
      - lines:
        - "Recibe en tu correo tu acceso personal a la aplicación de forma gratuita."
        - "Además te mantendremos informado de la últimas noticias, actualizaciones y mejoras sobre la herramienta para la gestión integral de carreteras."
    project:
      date: "Fecha"
      company: "Empresa"
      tags: "Etiquetas"
      client: "Cliente"
      website: "Web"
    sidebar-contact:
      title: "LICITACIONES"
      item1: "Conservación Viales"
      item2: "Zonas Verdes"
      item3: "Señalización Carreteras"
      call-to-action: "Nosotros te llamamos"
      open: "Abrir"
      close: "Cerrar"
    biddings:
      title: "Nuevas licitaciones"
      description: "gvSIG Roads tu software de carreteras que acompaña a tu empresa en las licitaciones"
      term: "Plazo"
      place: "Lugar"
      document: "Pliego"
    more: "Más info"
    details: "Detalles"
    goback: "Volver"

  en:
    title: "gvSIG Roads, free solution for the management of roads"
    # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
    legal-notice: "Legal Notice"
    office: "Our office"
    header:
      title: "gvSIG"
      title-highlight: "Roads"
      description:
      - lines:
        - Open source and interoperable solution
        - for the management of roads
    about:
      title: "What is gvSIG Roads?"
      description:
      - lines:
        - "gvSIG Roads is a full solution, which allows the management of the roads infrastructures both from its alphanumeric and geographical component, based on standards and free software."
        - "Deploying gvSIG Roads gives you a complete management system for the conservation and inventory of roads integrated with the features of the Spatial Data Infrastructures."
      # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
      headline: "Comprehensive maintenance management and maintenance of roads using free software with integrated mapping information."
    how:
      title: "gvSIG Roads Workflow"
      description: "It incorporates functionalities of graphic character that contribute the GEO concept as well as analysis tools and decision-making."
    features:
      title: ""
      description: ""
    features:
      title: "Technology platform"
      description: "Using the most widespread and contrasting technologies, with broad international support, and with a constant evolutionary curve."
    video:
      title:
      - lines:
        - "The best solution for the comprehensive"
        - "management of roads"
      headline: "Management of incidents, inventory and  workflow with gvSIG Roads"
    software:
      title: "Solution based on a suite of free applications"
      description:
      - lines:
        - "Free and interoperable"
        - ""
      tools:
        - name: gvSIG Desktop
          img: logo_gvsigdesktop.png
          url: http://www.gvsig.com
          description: "Software for the management of geographic information with cartographic precision"
        - name: gvNIX
          img: logo-gvnix-negativo.png
          url: http://www.gvnix.com
          description: "Tool for rapid Java web application development"
    portfolio:
      title: "CASE OF STUDY"
      description: "Projects and presentations of gvSIG Roads solution"
      subtitle: "Experience backs us up"
    clients:
      title: "DEVELOPED BY"
      description: "Organizations involved in the project"
    banner:
      title: "gvSIG Roads"
      description: "Full solution for the comprehensive management of roads"
      call-to-action: "I want to receive more information!"
    contact:
      title: "Do you want to use gvSIG Roads in your projects?"
      description:
      - lines:
        - "Great, good choice!"
        - "Just call or send us an email, as you wish, and we will get in touch with you as soon as possible."
      company: I'm a company
      council: I'm a council
    suscribe:
      title: "Do you want to see an gvSIG Roads demo?"
      email: "Your email *"
      email-message: "Please, enter your email address."
      button: " I want to access to the demo!"
      description:
      - lines:
        - "Subscribe and get your personal access to the application for free."
        - "Moreover, if you register we will keep you informed as to any novelties and special promotions on the tool for the comprehensive management of roads."
    project:
      date: "Date"
      company: "Company"
      tags: "Tags"
      client: "Client"
      website: "Website"
    sidebar-contact:
      title: "BIDDING"
      item1: "Conservation Vials"
      item2: "Green Areas"
      item3: "Road Signs"
      call-to-action: "Let us call you"
      open: "Open"
      close: "Close"
    biddings:
      title: "New biddings"
      description: "gvSIG Roads your roads software that help your company in biddings"
      term: "Term"
      place: "Place"
      document: "Document"
    more: "More info"
    details: "Details"
    goback: "Go Back"

# To include variable in liquid: {{ site.t[page.lang].header.title }}
# You can add translations group

# Links to include in top navigation
# For external links add external: true
links:
  en:
    solutions:
      title: How works
      url: "http://www.gvsigroads.com/en/#how-works"
    projects:
      title: Features
      url: "http://www.gvsigroads.com/en/#services"
    technologies:
      title: Technology
      url: "http://www.gvsigroads.com/en/#features"
    blog:
      title: Case of study
      url: "http://www.gvsigroads.com/en/#portfoliowrap"
      external: true
    contact:
      title: Contact
      url: "http://www.gvsigroads.com/en/#contact"
  es:
    solutions:
      title: Cómo funciona
      url: "http://www.gvsigroads.com#how-works"
    projects:
      title: Características
      url: "http://www.gvsigroads.com#services"
    technologies:
      title: Tecnología
      url: "http://www.gvsigroads.com#features"
    blog:
      title: Casos de éxito
      url: "http://www.gvsigroads.com#portfoliowrap"
      external: true
    contact:
      title: Contacto
      url: "http://www.gvsigroads.com#contact"

include: [".htaccess"]
# ["_posts/en/features","_posts/es/features","_posts/es/about", "_posts/en/about", "_posts/es/how", "_posts/en/how", "_posts/es/services", "_posts/en/services",
exclude: ["vendor", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]